apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: K8S_NAMESPACE
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: shared-vault-secret-store
  target:
    name: db-credentials
    creationPolicy: Owner
    template:
      data:
        TNS_ADMIN: "/opt/db-wallet"
        DB_URL: "oracle+oracledb://{{ .username }}:{{ .password }}@{{ .service }}?wallet_location=/opt/db-wallet&wallet_password={{ .wallet_password }}"
        DB_USERNAMES: "{{ .username | toJson }}"
        DB_PASSWORDS: "{{ .password | toJson }}"
        TNS_NAME: "{{ .service }}"
        DB_WALLET_PASSWORD: "{{ .wallet_password }}"
        BASE_URL: "{{ .base_url }}"
  dataFrom:
  - extract:
      key: PROJ_VAULT_SECRET_NAME
  
