apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-admin-credentials
  namespace: K8S_NAMESPACE
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: shared-vault-secret-store
  target:
    name: db-admin-credentials
    creationPolicy: Owner
    template:
      data:
        username: ADMIN
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: ADB_ADMIN_SECRET_NAME
  
